# 11.异常、断言、日志和调试

### 11.1 处理错误

#### 11.1.1 异常分类

|      |       |  Throwable  |           |                  |
| ---- | :---: | :---------: | :-------: | :--------------: |
|      | Error |             | Exception |                  |
|      |       | IOException |           | RuntimeException |

- 未检查异常（unchecked）：派生于Error或RuntimeException类的所有异常.
- 已检查异常（checked）：其他的异常。

抛出异常：

1. 找到一个合适的异常类。
2. 创建这个类的一个对象。
3. 将对象抛出。

#### 11.1.4 创建异常类

1. 继承异常超类。
2. 添加构造器。

### 11.2 捕获异常

#### 11.2.1 捕获多个异常

在Java 7中，同一个catch子句可以捕获多个异常类型，只有当捕获的异常类型彼此之间不存在子类关系时才需要这个特性。

```java
try {
    
} catch (异常1 | 异常2 | ... e){
    
}
```

捕获多个异常时，异常变量隐含为final变量。不能为e赋不同的值。

#### 11.2.3 finally子句

释放资源。

try可以只有finally语句，而没有catch语句。

建议独立使用try/catch和try/finally语句块。

```java
InputStream in = ...;
try{
    try{
        code might throw exceptions
    }finally{
        in.closed();
    }
}catch(Exception e){
    show error message
}
```

```java
InputStream in = ...;
Exception ex = null;
try{
    try{
        code might throw exceptions
    }catch(){
        ex = e;
        throw e;
    }
}finally{
    try{
        in.closed();
    }catch(Exception e){
        if(ex == null) throw e;
    }
}
```

#### 11.2.4 带资源的try语句

```java
try(Resource res=...){
    
}
```

try退出时，会自动调用`res.closed();`。

上一节已经看到，如果try块抛出一个异常，而且close方法也抛出一个异常，这就会带来一个难题。带资源的try语句可以很好地处理这种情况。

原来的异常会重新抛出，而close抛出的异常会“被抑制”。这些异常将自动捕获，并由addSuppressed方法增加到原来的异常。如果对这些异常感兴趣，可以调用getSuppressed方法，它会得到从clone方法抛出并被抑制的异常列表。

带资源的try自身也可以有catch，finally。这些子句会在关闭资源后执行。

### 11.3 使用异常机制的技巧

1. 异常处理不能代替简单的测试。
2. 不要过分地细化异常。
3. 利用异常层次结构。
4. 不要压制异常。
5. 在检测错误时，“苛刻”要比放任好。
6. 不要羞于传递异常。
